from pathlib import Path
import re,shutil,json
H=Path(__file__).resolve().parent;D=H/'manuscript';OLD=H.parent/'51_evidence_figures_20261001/manuscript'
s=(OLD/'manuscript_v5.md').read_text()
for p in (OLD/'assets').glob('*'):shutil.copy2(p,D/'assets'/p.name)
for p in OLD.glob('Supplementary_Table*.tsv'):shutil.copy2(p,D/p.name)
s=s.replace(s.splitlines()[0],'# Lineage structure and molecular diversity of microbial strategies across terrestrial Mars analogues',1)
start=s.index('Microbial life in terrestrial');end=s.index('\n\nKeywords:',start)
s=s[:start]+'''Microorganisms in terrestrial Mars analogue environments must maintain cellular integrity while acquiring energy and carbon. Whether shared strategy labels correspond to similar genetic repertoires remains unresolved. We compared lineage structure and source-associated variation across seven metagenome-assembled genome catalogues, examined specified gene combinations in an additional dryland catalogue and characterized an AI-prioritized protein family outside the assigned KO repertoire. Of 4,213 original genomes, 3,904 passed primary quality thresholds. Under source-preserving null models, 42 of 43 variable bacterial maintenance markers and 14 of 15 energy markers were phylogenetically clustered. Maintenance and energy portfolios differed in source association, but their paired difference was uncertain under lineage-block Bayesian reweighting and sensitive to molecular composition. Follow-up analyses resolved unequal associations among specific systems, including potassium acquisition and regulation. In stringent dryland genomes, 35 of 38 KdpABC co-detections formed same-strand clusters within 10 kb, while limited cross-site lineage overlap constrained ecological replication. The DPFQ008 case comprised 63 proteins with conserved cytochrome-c-like features and lineage-associated sequence variation, supporting an electron-transfer-related hypothesis without resolving biochemical function. Together, these results distinguish shared strategy labels from the lineage-associated molecular repertoires that encode them. They provide a comparative-genomic basis for evaluating adaptation in Mars analogues and for prioritizing molecular hypotheses, while environmental drivers and realized resource use remain to be established.''' +s[end:]
s=s.replace('Keywords: Mars analogues; microbial strategies; environmental constraints; resource acquisition; phylogenomics; Bayesian analysis','Keywords: Mars analogues; microbial strategies; phylogenomics; cellular maintenance; energy acquisition; protein function prediction')
intro='''Three related questions connect environmental comparisons to molecular adaptation. First, do shared maintenance and energy-acquisition functions have similar distributions across lineages? Second, do source-associated differences reflect broad strategy categories or particular molecular systems? Third, can proteins outside assigned functional repertoires be resolved into candidate components of survival and resource-acquisition repertoires? Functional redundancy and thermodynamic convergence at community scale do not establish equivalent genetic implementations within organisms, nor independent evolutionary origins of shared traits [9, 10, 11]. The first two questions can be investigated with annotated genomic repertoires; the third requires additional sequence, structural and evolutionary evidence.

These questions operate at a common genomic scale but have different evidential requirements. Marker detection measures encoded potential rather than expression or flux. Atmospheric-gas oxidation requires more specific evidence than a generic hydrogenase or CO-associated annotation [12]. Conversely, a protein without an assigned KO need not lack recognizable domains or belong to a new biochemical class. AI-assisted function prediction can help prioritize such sequences for investigation [40, 41], while motif, domain, genomic-context and phylogenetic analyses determine which functional interpretation is supportable. A molecular candidate can be informative before its ecological effect is established.

Here we examine the lineage structure and molecular composition of microbial survival and resource-acquisition repertoires across seven source catalogues. We test how a maintenance–energy comparison changes when broad categories are resolved into specified gene combinations, evaluate additional dryland genomes for molecular and ecological support, and characterize the AI-prioritized DPFQ008 family as a complementary candidate-function case. These analyses distinguish the distribution of known capabilities from the interpretation of unassigned proteins. Environmental measurements and sampling provenance delimit the conditions under which their genomic organization can inform questions about adaptation.''' 
a=s.index('Three explanations consequently merit distinction.');b=s.index('\n\n## Results',a);s=s[:a]+intro+s[b:]
# Keep all existing primary numerical analyses, but give the molecular example its own result.
s=s.replace('### Source structure is concentrated in potassium-associated combinations','### Specific gene combinations resolve heterogeneous source associations')
s=s.replace('### The additional dryland catalogue supports combinations but not equivalent ecological replication','### Dryland genomes extend molecular support while limiting ecological comparison')
s=s.replace('### Existing source profiles and measured environmental associations address different contrasts','### Source-associated repertoires are not explained by the available environmental contrasts')
a=s.index('An exploratory cytochrome-c-like family, DPFQ008,');b=s.index('\n\n## Discussion',a)
s=s[:a]+'''### An AI-prioritized candidate adds molecular resolution beyond assigned KO repertoires

The preceding analyses describe combinations of assigned markers. A complementary discovery analysis investigated whether conventionally unresolved proteins could be assigned more specific molecular hypotheses. DPFQ008 emerged from this AI-assisted prioritization and was examined with existing sequence profiles, domain and topology annotations, structural prediction and genomic context. The 359-amino-acid representative contained two CXXCH motifs, two non-overlapping cytochrome-c-like profile regions (97–230 and 250–359) and two predicted transmembrane segments (Fig. 6a). Its two InterPro accessions represent a domain and a superfamily annotation; their count is not a count of independent domains. These annotations provide a recognizable molecular identity beyond the absence of a KO assignment; they do not establish a previously unknown biochemical function.

The AI predictors did not provide concordant high scores for the electron-transfer term GO:0009055. The retained ProtNote score was 0.815, whereas mDeepFRI gave 0.114; DPFunc ranked the term 648th with a raw score of 8.26 × 10⁻⁶. These outputs are method-specific and were not calibrated as comparable probabilities of this candidate’s true function. The functional hypothesis therefore rests on the subsequent molecular evidence rather than an assertion of agreement among AI methods.

The strict profile-HMM search recovered 63 proteins from 61 MAGs and 58 ANI95 groups in four catalogues: 56 proteins from Qaidam, three from Mauna Loa, two from Australian lava tubes and two from Alaskan permafrost. Sixty-two proteins were assigned to Actinomycetota and one to Gemmatimonadota. All 52 proteins at least 300 amino acids long retained two CXXCH motifs; the remaining eleven included two with two motifs, seven with one and two with none. Short length alone did not establish assembly truncation. Five seed-profile sensitivity folds recovered all 20 held-out discovery sequences, produced 59–69 strict hits per fold and recovered 60 of the 63 full-profile hits in at least four folds. These are internal profile-stability results rather than an external benchmark of functional accuracy.

Across 58 ANI95 representatives, gene-tree and host-tree patristic distances were correlated (Spearman r = 0.666; 9,999 label permutations, P = 0.0001). Removing Qaidam–Qaidam distance pairs left 378 pairs and a correlation of 0.305 (P = 0.0001; Fig. 6b). This sensitivity retains pairs linking Qaidam and non-Qaidam representatives; it is not an independent non-Qaidam validation set. Detection in multiple environments therefore coexisted with lineage-associated sequence variation, without resolving the relative contributions of vertical inheritance and horizontal transfer.

Cytochrome/haem-related annotations occurred within the specified neighbourhood of 54 of 63 proteins and 53 of 61 carrier MAGs. The archived within-MAG matched null gave a mean of 3.752 positive MAGs and a central 95% range of 1–8 across 100,000 permutations (Fig. 6c). Neighbourhood evidence contributed to candidate prioritization, so this contrast is conditional descriptive support rather than an independent confirmation of function. Together, the molecular features support an electron-transfer-associated hypothesis for DPFQ008. Substrate, donor–acceptor partners, activity and any contribution to the maintenance–energy contrast remain unresolved.''' +s[b:]
# Replace discussion progression, retaining the concrete Mars-mapping section.
a=s.index('### Molecular organization changes');b=s.index('### Implications for Martian life detection',a)
disc='''### Shared strategy labels conceal lineage-associated molecular diversity

The comparative analyses identify two features of microbial strategies across the sampled Mars analogue catalogues: widespread maintenance and energy markers retain strong lineage structure, and source associations differ substantially among their constituent molecular systems. Their combination matters ecologically. Similar functional labels do not imply interchangeable genomic repertoires, yet source differences alone do not identify the environmental process that generated them. The comparison therefore needs to retain both the phylogenetic background and the particular capabilities represented by each functional category.

The maintenance–energy contrast illustrates this distinction. Its positive bacterial point estimate did not yield a stable general ordering under source-composition and module-weighting sensitivities. Resolving the solute and ion module exposed unequal contributions from potassium-associated transport and regulation, compatible-solute transport and biosynthetic markers. Kdp is one informative example within this heterogeneity, rather than an explanation of all maintenance or a salt-tolerance-specific marker. Genomic co-detection and local organization strengthen the description of a specified implementation, but neither measures physiological investment or shows why it was retained in a habitat.

Recent desert and brine studies provide complementary resource contexts [7, 8]. Aridity-associated inorganic energy acquisition and metabolic diversity in resource-heterogeneous brines can both motivate tests of how survival and acquisition capabilities are combined. Our results add a genomic consideration to that question: comparisons based on broad categories can depend strongly on the molecular systems and lineages that represent them. They do not establish that water limitation, ionic stress and carbon supply act through the same genes across all analogue environments.

### AI-assisted discovery complements comparisons of annotated functions

DPFQ008 supplies a second route to molecular resolution. Instead of subdividing an annotated strategy, it follows an initially unresolved family toward a specific functional hypothesis. Its conserved motifs, cytochrome-c-like annotations and lineage-associated sequence variation support an electron-transfer-related interpretation. The family thus belongs in a study of genomic strategy organization even though it has not been linked to the source-level maintenance–energy contrast. Its role is a molecular case study, not evidence that an unknown gene explains an aggregate ecological pattern.

This distinction also clarifies the contribution of AI. Predictions guide attention to sequences worth investigating; confidence comes from examining what additional sequence, domain, structural and evolutionary information supports or contradicts the hypothesis. Agreement among predictors is not automatically independent evidence when they share inputs or domain information. Likewise, the DPFQ008 neighbourhood contrast remains conditional on discovery and selection. The present analysis supports a candidate identity, while novelty of biochemical function, reaction partners and condition-specific roles require additional discriminating evidence. Absence of a KO assignment should not be equated with absence of recognized protein biology.

### Environmental mechanisms require comparable resources and lineages

Explaining these genomic patterns requires distinguishing environmental constraints, resource supply and phylogenetic background within a design that can separate them. Source labels combine environment, geography, evolutionary history and study methods. The clear conditional Bayesian source profiles and uncertain within-Qaidam associations address different contrasts; neither establishes that environment is unimportant. Water content, water activity and conductivity are not interchangeable, and carbon stocks do not directly measure usable supply.

The additional dryland catalogue reveals a practical limit of public-genome synthesis. Local gene organization can be evaluated even when stringent cross-site family support is inadequate for a corresponding ecological comparison. Coassembly parentage and uneven geographic labels further constrain the independent units. Additional soil or desert genomes are most informative when they supply a missing resource contrast within comparable lineages, rather than merely increasing the number of genomes. Bayesian partial pooling can represent uncertainty in such comparisons but cannot separate environmental and study effects when their design is confounded.

A discriminating computational extension would first validate molecular identity and detection, then assess the frozen combinations or candidate family in independently selected public sequence collections. Where matched environmental measurements are available, lineage and technical baselines can be compared with models that add constraint, resource and interaction terms using site- or study-level holdout. Candidate discovery and evaluation must remain separate. This approach allows known alternatives, lineage conservation or detection error to explain a pattern without requiring an unknown mechanism, while retaining condition-specific roles as testable possibilities.

'''
s=s[:a]+disc+s[b:]
s=s.replace('The central unresolved issue is which environmental and resource contrasts predict differences in specific gene combinations beyond lineage and sampling background. The present results locate a molecular source of aggregate heterogeneity and establish the limits of its independent support. They provide a genome-resolved starting point for studying adaptation across Mars analogue systems, while leaving environmental causation and realized resource use open to tests with matched public data.','The study connects repertoire-level comparisons with two forms of molecular resolution: specified combinations of known genes and a candidate family beyond assigned KO repertoires. Their shared lineage context provides a coherent basis for asking how microbial strategies vary across Mars analogues. Determining which environmental resources explain that variation remains the next ecological test; estimating activity or resource-use performance requires distinct endpoints.')
# Methods: restore the exact archived family procedure, with selection caveats explicit.
method='''### AI-assisted candidate interpretation and DPFQ008 characterization

DPFQ008 was evaluated as a case from the principal candidate-prioritization analyses in the existing AI-assisted workflow, using ProtNote sequence/function predictions, mDeepFRI, DPFunc domain-guided predictions and an ESMFold model [40, 41, 42, 43]. Predictions were interpreted together with conventional InterPro and topology annotations rather than as confirmed biochemical assignments. The retained workflow used the ProtNote seed-42 checkpoint and mDeepFRI v1.1.8. DPFQ008 belonged to the mainline-relevant, low-mDeepFRI candidate tier. The adapted DPFunc input preparation used ESMFold coordinates, ESM2-650M residue embeddings and a 22,369-dimensional InterPro vector; the raw outputs were not treated as calibrated candidate-function probabilities. Candidate-level scores and source records are retained in Supplementary Table S3. Neighbourhood information participated in prioritization, and the selected family was not treated as an unbiased sample of all unassigned proteins or an independent test of AI accuracy.

A profile HMM was built with HMMER from the MAFFT alignment of the frozen 20-member MMseqs50 discovery family and searched against the 13,461,537-protein primary catalogue. The strict set required domain independent E value ≤10⁻¹⁰ and target coverage ≥0.70. CXXCH motifs were read directly from sequences. Deterministic five-fold seed sensitivity used 16 training and four held-out sequences per fold, with the same catalogue and thresholds. This evaluated seed dependence, not external sensitivity or specificity.

MAFFT alignment of the 63 strict proteins yielded 586 positions. IQ-TREE2 inferred the gene tree under LG+F+I+G4 with 1,000 ultrafast-bootstrap and 1,000 SH-aLRT replicates. One hit per ANI95 representative was selected by lowest domain independent E value, greatest target coverage and lexical protein identifier, yielding 58 representatives. Gene- and host-tree patristic distances were compared with a Spearman Mantel statistic and 9,999 label permutations. The dominance sensitivity removed Qaidam–Qaidam pairs, retaining both mixed-source pairs and non-Qaidam pairs.

Context was defined from existing eggNOG annotations in the five upstream and downstream genes on the same contig, using cytochrome-, CXXCH-, haem/heme- or porphyrin-related annotations. Controls were conventionally unresolved proteins from the same MAG within 20% of target length and with the same complete versus contig-truncated window state; windows overlapping target windows were excluded. One control per target stratum was sampled in each of 100,000 fixed-seed draws, aggregating to carrier MAGs for the main comparison and retaining a protein-level sensitivity. Plus-one empirical probabilities describe this matched null conditional on the selected family; selection using context precludes an independent functional-confirmation interpretation. All candidate analyses are reused completed analyses, and no new predictions or family selection were performed for this integration.

'''
s=s.replace('### Independent recruitment and supplementary analyses',method+'### Independent recruitment and supplementary analyses')
s=s.replace('geNomad v1.9 mobile-context analyses [39], protein-family predictions and the nonpaired amplicon analyses remain supplementary and do not substitute for ecological holdout validation.','geNomad v1.9 mobile-context analyses [39] and the nonpaired amplicon analyses provide secondary evidence and do not substitute for ecological holdout validation.')
# Insert the restored full case figure; explicitly distinguish visual prominence from claim strength.
fig='''![DPFQ008 candidate molecular and lineage evidence](assets/figure6_DPFQ008.png)

Figure 6 | AI-assisted prioritization and molecular characterization of a lineage-structured electron-transfer candidate. A, Representative sequence architecture, two CXXCH motifs, cytochrome-c-like InterPro support, predicted transmembrane segments and one complete ±5-gene window. InterPro entries do not count independent physical domains. B, Existing 63-protein gene tree with source, motif and context tracks; distance correlations use 58 ANI95 representatives. “Pairs excluding Q–Q” removes Qaidam–Qaidam pairs but retains mixed-source pairs. C, Existing within-MAG matched context null, with 53/61 carrier MAGs context-positive. Context contributed to selection, so the null contrast is conditional evidence, not independent confirmation of function or ecological adaptation. No biochemical activity, new pathway or causal link to the maintenance–energy contrast is established.

'''
s=s.replace('![Environmental constraints', '![Environmental constraints',1)
anchor='![Conceptual framework'
# Locate first supplementary asset regardless of its alt label.
m=re.search(r'!\[[^\n]+\]\(assets/figureS1[^\n]+\)',s);assert m;s=s[:m.start()]+fig+s[m.start():]
# Family evidence accompanies the restored main-text analysis.
s=s.replace('## References','Supplementary Table S3 | DPFQ008 candidate evidence, profile recovery, sequence architecture and lineage/context source data. Existing discovery and characterization files are retained with original identifiers; candidate selection and conditional tests remain explicitly distinguished.\n\n## References')
s+='''\n40. Char S, Corley N, Alamdari S et al. ProtNote: a multimodal method for protein–function annotation. Bioinformatics 2025;41:btaf170. https://doi.org/10.1093/bioinformatics/btaf170

41. Wang W, Shuai Y, Zeng M, Fan W, Li M. DPFunc: accurately predicting protein function via deep learning with domain-guided structure information. Nature Communications 2025;16:70. https://doi.org/10.1038/s41467-024-54816-8

42. Lin Z, Akin H, Rao R et al. Evolutionary-scale prediction of atomic-level protein structure with a language model. Science 2023;379:1123–1130. https://doi.org/10.1126/science.ade2574

43. Maranga M, Szczerbiak P, Bezshapkin V et al. Comprehensive functional annotation of metagenomes and microbial genomes using a deep learning-based method. mSystems 2023;8:e01178-22. https://doi.org/10.1128/msystems.01178-22
'''
# Renumber references by first textual use, including new AI methods.
body,refs=s.split('## References',1);entries={int(m.group(1)):m.group(2).strip() for m in re.finditer(r'(?m)^(\d+)\. (.*?)(?=\n\n\d+\. |\Z)',refs,re.S)}
order=[]
for m in re.finditer(r'\[(\d+(?:,\s*\d+)*)\]',body):
 for x in map(int,m.group(1).split(',')):
  if x not in order:order.append(x)
assert set(order)==set(entries),(set(entries)-set(order));mapping={k:i+1 for i,k in enumerate(order)}
body=re.sub(r'\[(\d+(?:,\s*\d+)*)\]',lambda m:'['+', '.join(str(mapping[int(x)]) for x in m.group(1).split(','))+']',body)
s=body+'## References\n\n'+'\n\n'.join(f'{mapping[k]}. {entries[k]}' for k in order)+'\n'
s=s.replace('coincided with inherited lineage structure','coincided with phylogenetic structure')
(D/'manuscript_v6.md').write_text(s);(H/'host/reference_renumbering.json').write_text(json.dumps(mapping,indent=2))
print('v6 complete semantic manuscript; existing analyses retained; family case restored.')
