from pathlib import Path
import re,shutil
H=Path(__file__).resolve().parent;B=H.parent;D=H/'manuscript';D.mkdir(exist_ok=True)
s=(B/'34_integrated_manuscript_20260929/manuscript_NEE_ISME_v3.md').read_text()
s=s.replace('# Microbial survival and resource-acquisition strategies across terrestrial Mars analogues','# Genomic organization of microbial survival and resource acquisition across terrestrial Mars analogue systems')
s=re.sub(r'Integrated working manuscript v3.*?\n\nRuxin', 'Ruxin',s,flags=re.S)
def section(start,end,new):
 global s
 a=s.index(start);b=s.index(end,a);s=s[:a]+new.strip()+'\n\n'+s[b:]
section('## Abstract','Keywords:', '''## Abstract

Microbial life in terrestrial Mars analogue systems must combine cellular maintenance with access to energy and carbon, but shared functional labels need not imply similar genetic repertoires. We compared lineage structure and source-associated variation in selected genomic strategies across seven catalogues and examined their molecular organization in an additional global dryland catalogue. Of 4,213 original metagenome-assembled genomes, 3,904 passed primary quality thresholds. Under source-preserving null models, 42 of 43 variable bacterial maintenance markers and 14 of 15 energy markers were phylogenetically clustered. Among 2,693 bacterial representatives, maintenance and energy portfolios had source partial R² values of 5.01% and 2.19%, respectively. Their paired difference was uncertain under lineage-block Bayesian reweighting (2.81 percentage points; 95% range −1.02 to 5.28) and sensitive to aggregation within the solute and ion maintenance module. Follow-up decomposition statistically localized much of this source structure to Kdp-associated potassium acquisition and regulation. KdpABC marker co-detection retained a descriptive source association within cross-source family support, whereas the additional dryland catalogue lacked sufficient stringent family-level support for an equivalent comparison. Sampling provenance further distinguished regional analogue relevance from the local conditions represented by individual or coassembled genomes. The results identify lineage-structured differences in specified gene combinations, but do not establish universal maintenance convergence, environmental causation or alternative pathways supplied by unknown genes. Resolving adaptation across Mars analogue systems requires linking these molecular units to independently supported environmental contrasts, rather than treating habitat labels or aggregate marker counts as mechanisms.''')
s=s.replace('Here we integrate comparative genomics across seven Mars-analogue catalogues with source-resolved environmental evidence. Completed analyses characterize the lineage structure and source differentiation of selected maintenance and energy functions, assess their sensitivity to annotation and genome quality, and estimate source profiles and within-source associations using Bayesian models. We also organize measured environmental and resource variables at their actual sampling levels and connect existing carbon-fixation route evidence to those units. This retrospective ecological integration establishes what the current data explain and what remains distinguishable only through additional computational comparisons. It provides a basis for relating microbial strategies to particular Martian settings without claiming demonstrated life, activity or resource-production performance on Mars.', '''Here we compare genome-encoded maintenance and resource-acquisition configurations across seven source catalogues, then resolve the sensitivity of a broad maintenance–energy contrast to its constituent molecular systems. We ask whether source differentiation remains distinguishable from lineage structure, whether an aggregate contrast represents several functional groups or a more specific combination, and whether an additional dryland catalogue supplies comparable independent support. A separate provenance audit evaluates the dimensions of Mars analogy and the spatial units represented by those genomes. This design addresses the genomic organization of candidate strategies; it does not assume that a source label measures a particular environmental constraint or that marker occurrence establishes activity.''')
section('### Source differentiation differs between functional categories and domains','### Bayesian source profiles', '''### The maintenance–energy contrast depends on uncertainty and aggregation

Among 2,693 bacterial representatives in 30 eligible cross-source lineage blocks, source partial R² was 5.0064% for maintenance and 2.1932% for energy modules. The maintenance-minus-energy difference was 2.813 percentage points. Paired lineage-block Bayesian reweighting gave a 95% conditional range of −1.016 to 5.280 percentage points; the corresponding stringent-quality analysis of 813 representatives in 24 blocks gave a difference of 4.130 points and a range of 1.297 to 8.071. Multiplying lineage weights by independent source weights yielded ranges crossing zero in both quality strata. These ranges describe sensitivity within the observed catalogues and grouping assumptions, rather than a posterior environmental effect across all Mars analogues (Fig. 2).

Restoring correctly assigned functions gave a primary difference of 2.226 percentage points, again with a lineage-reweighting range crossing zero. Source omissions and individual lineage-block omissions retained the positive point direction, but did not resolve uncertainty about a general category ordering. The primary archaeal comparison had the opposite ordering, with source partial R² values of 8.21% for maintenance and 17.01% for energy. Its 31-representative stringent portfolio subset did not resolve the contrast. The bacterial result therefore does not support a universal difference between all maintenance and energy functions.

The bacterial comparison comprised five maintenance modules and two variable energy modules; its light-associated module was invariant. The solute and ion maintenance module had the largest source partial R², 12.322%. Omitting it reduced the maintenance-minus-energy difference to 0.441 percentage points. In a post-result sensitivity analysis, equally weighting that module's five constituent subgroups reduced the difference to 0.319 points, with a lineage-reweighting range of −2.807 to 2.553. Neither weighting is an established measure of physiological investment. Together these analyses show that the broad category contrast depends on which molecular capabilities are counted and how their coverage is aggregated.

### Source structure is concentrated in potassium-associated combinations

The five solute and ion subgroups had markedly different source associations. In the original primary bacterial analysis, source partial R² was 44.745% for Kdp-associated potassium acquisition and regulation, compared with 0.138–6.381% for the other four subgroups. Equal KO weighting assigned the five subgroups weights proportional to 1:3:3:5:3. Equal subgroup weighting reduced the aggregate module's source partial R² from 12.322% to 2.145%. An exact residual-covariance decomposition showed negative cross terms between several source-associated subgroup components. Such statistical cancellation does not demonstrate competition for cellular resources or replacement of one pathway by another.

To distinguish gene coverage from specified combinations, we separated KdpABC transport markers from KdpDE regulatory markers and evaluated ProVWX, EctABC, EctD and BetAB separately. Within 1,061 representatives from 30 families meeting an exploratory cross-source support criterion, simultaneous detection of the three KdpABC markers retained a descriptive source partial R² of 18.720% after family and quality adjustment. KdpDE co-detection yielded 21.647%, whereas ProVWX, EctABC and BetAB yielded 1.249%, 4.296% and 0.397%, respectively. These associations do not depend solely on counting three Kdp subunits independently (Fig. 3).

KdpABC co-detection nevertheless does not establish a complete KdpFABC operon: KdpF was outside the selected panel, and genomic adjacency was not evaluated here. Kdp participates in potassium homeostasis and is regulated at expression and post-translational levels; its presence is not a salt-tolerance-specific marker or evidence of use [31]. Likewise, partial EctABC or BetAB support does not establish an unknown substitute, because upstream requirements, alternative known routes and detection uncertainty remain unresolved. The follow-up identifies specific molecular candidates for interpretation without assigning the original source contrast to a measured environmental driver.

### The additional dryland catalogue supports combinations but not equivalent ecological replication

The additional catalogue contained 826 quality-screened MAGs, including 783 Bacteria and 43 Archaea. Excluding flagged background genomes and ANI95 clusters shared with the existing 4,095-genome comparison pool, then choosing quality-ranked bacterial representatives independently within each quality stratum, retained 739 primary and 154 stringent representatives. These numbers are not additions to the original 2,693-genome model. Their collection labels covered 25 and 21 sampling groups, respectively, within one additional study.

Among stringent representatives with at least one specified KdpABC marker, 38 of 43 contained all three markers; for ProVWX, 17 of 18 contained all three. Corresponding EctABC and BetAB counts were 1 of 11 and 10 of 39. The marker structure is consistent with multicomponent systems, but does not establish ecological convergence or absence of alternative biosynthetic routes. Conditional site-weighted Bayesian reweighting placed the KdpABC co-detection fraction between 72.8% and 96.8% and ProVWX between 73.7% and 99.9%; these are not tests of equality with the original catalogue.

At the same family-level common-support gate, the primary dryland comparison retained only 147 representatives in five families across 22 sampling groups. The KdpABC co-detection site partial R² was 15.125%, falling to 0.147% after degrees-of-freedom adjustment. No stringent family or order subset met the gate. The adjusted value is not a cross-validated prediction score, and insufficient support does not establish absence of an environmental relationship. It does prevent this catalogue from being presented as an equivalent replication of the original seven-source contrast.

### Mars analogue relevance and sampling support are distinct properties

All 75 deposited dryland field samples were linked to 25 collection labels, but those labels did not represent a uniform spatial scale. The primary representative genomes included 561 assemblies linked to three parent soil samples and 178 linked to a single parent; the stringent subset contained 110 and 44, respectively. Parent samples under Drass, Kalahari, Richtersveld and North Australian Desert labels spanned approximately 54.6, 37.8, 23.6 and 14.0 km. Identical deposited coordinates at other sites describe metadata precision rather than proof that the samples occupied the same microhabitat. Coassembly parentage does not provide abundance or locate a recovered genotype in each parent sample.

We therefore treated regional analogue evidence, sample substrate and sampling geometry as separate attributes. Six regional candidates prioritized for a bounded literature audit—Atacama, McMurdo Dry Valleys, Mount Seuss, Mojave, Namib and Negev—contained 301 primary and 70 stringent representatives. These counts describe an audit subset, not a final six-site definition of Mars analogues. Regional evidence cannot certify a deposited Nevada Mojave soil as the carbonate bedrock examined in California, or a Yungay surface soil as the wet clay horizon reported at approximately 30 cm depth [33, 34, 35]. High-elevation Dry Valley ground-ice studies likewise do not establish the ice state at our deposited McMurdo point [36]. The Mount Seuss comparison has same-region soil ecological evidence [37], whereas the bounded Namib and Negev sources address aeolian cementation and radar detection, respectively [38, 39]. These sources establish different dimensions of analogy rather than interchangeable ecological environments. The remaining 19 labels were retained as broader dryland context with unresolved analogue-specific scope, rather than declared non-analogues.

Even in the six-candidate subset, the cross-group support criterion retained only 41 primary representatives in two families; no stringent class, order or family subset met it. These results delimit an available design, not a biological absence. Analogue eligibility and statistical comparability must both be established before asking which environmental constraint explains a combination. Regional analogue literature and its correspondence limits are recorded separately (Supplementary Table S1).''')
# replace selected old headline argument, retain completed Bayesian results as secondary evidence
s=s.replace('### Bayesian source profiles do not identify the measured environmental drivers','### Existing source profiles and measured environmental associations address different contrasts')
s=s.replace('(Fig. 3).','(Supplementary Fig. S1).',1) if False else s
# The original Bayesian paragraph is uniquely matched; do not redirect the new Kdp Fig.3.
s=s.replace('Prior-sensitivity medians ranged from 17.14 to 17.93 points (Fig. 3).','Prior-sensitivity medians ranged from 17.14 to 17.93 points (Supplementary Fig. S1). These completed analyses are retained as secondary source-profile evidence; their aggregate osmotic endpoint is subject to the molecular-composition limitation identified above.')
section('### From shared functions to conditional strategy combinations','### Explaining a source effect', '''### Molecular organization changes the interpretation of broad strategy labels

Shared maintenance labels concealed unequal source structure among the selected molecular capabilities. Strong phylogenetic clustering was accompanied by source-associated differences, but the paired maintenance–energy contrast remained uncertain under source composition sensitivity and changed substantially when the solute and ion module was reweighted. The most specific supported observation is therefore heterogeneity among gene combinations, including Kdp-associated transport and regulation, rather than a general failure of maintenance convergence. Gene coverage and co-detection answer different questions and neither alone measures physiological investment.

This distinction sharpens the ecological question. Potassium acquisition, compatible-solute transport and solute biosynthesis can contribute to cellular maintenance through different physiological requirements. A shared label should not be assumed to make their responses to a resource or constraint interchangeable. Kdp co-detection offers a concrete candidate for subsequent sequence-context and environmental tests, but its post-result identification and the absence of direct potassium-availability contrasts preclude calling it the mechanism underlying the catalogue pattern. Total potassium, if available, would also require distinction from bioavailable potassium.

Recent desert and brine studies provide complementary resource contexts [7, 8]. Their observations motivate asking when organisms encode inorganic energy acquisition, carbon assimilation and heterotrophic capabilities together. They do not establish that different study-level patterns result from the same environmental axis. Our comparison preserves these separate functions and avoids reducing them to mutually exclusive autotroph and heterotroph strategies. A mechanistic account must explain the particular combination within its lineage and sampling context.''')
s=s.replace('A decisive extension would compare survival and acquisition traits against separately measured constraints and resource descriptors, accounting for their support ranges and sampling hierarchy. Public soil MAGs are potentially valuable when they add a missing contrast, such as comparable water limitation across different carbon contexts.', 'A decisive extension would compare the specified molecular combinations against separately measured constraints and resource descriptors, accounting for their support ranges and sampling hierarchy. The dryland extension demonstrates why a large public MAG collection is not automatically a crossed design: many genomes derive from coassemblies, regional labels differ in spatial extent, and stringent common-lineage support is sparse. Public soil MAGs are valuable when they add a missing contrast, such as comparable water limitation across different carbon contexts.')
s=s.replace('The central unresolved issue is which combinations of constraints and resources predict strategy differences beyond lineage and source background. Our integrated evidence makes this question concrete: genomic configurations vary, environmental support is heterogeneous, and a sparse carbon-fixation endpoint cannot alone carry the proposed interaction. Addressing the question requires targeted public-data contrasts and reaction definitions that connect the observed variation to mechanisms. It does not require abandoning the Mars-analogue focus or presenting unmeasured fluxes as established adaptations.', 'The central unresolved issue is which environmental and resource contrasts predict differences in specific gene combinations beyond lineage and sampling background. The present results locate a molecular source of aggregate heterogeneity and establish the limits of its independent support. They provide a genome-resolved starting point for studying adaptation across Mars analogue systems, while leaving environmental causation and realized resource use open to tests with matched public data.')
s=s.replace('This manuscript reuses completed analyses and adds a measurement-resolved evidence inventory and linkage of existing route calls.', 'This study combines the original comparative-genomic analyses with paired uncertainty estimation, post-result module decomposition, specified gene-combination diagnostics and an additional dryland provenance audit.')
s=s.replace('The contrast was R²energy − R²maintenance.', 'For the paired analyses reported here, the contrast is R²maintenance − R²energy; historical outputs using the reverse sign were converted explicitly.')
insert='''### Paired uncertainty and molecular decomposition

For each of 2,000 reweighting replicates, independent Exp(1) weights were assigned to observed lineage blocks, shared by all genomes in a block and all functional endpoints. Reduced and full weighted models were refitted, with response scaling recalculated under those weights. Normalized weights correspond to a Bayesian bootstrap on the observed blocks [32]. A separate sensitivity multiplied these weights by independent source-level Exp(1) weights, examining dependence on the observed source composition rather than guaranteeing population-level coverage for the nonlinear R² contrast. The random seed was 20261001. The blocks are not randomly sampled independent evolutionary or environmental units; all intervals are conditional on this approximation and the observed catalogues.

Post-result diagnostics omitted individual modules, KOs and lineage blocks, retained all module reassignment comparisons and compared KO weighting with equal weighting of the five existing solute and ion subgroups. Equal subgroup weighting was not substituted as a new primary endpoint. For residual covariance matrices C_reduced and C_full and subgroup weight vector w, source partial R² was wᵀ(C_reduced − C_full)w / (wᵀC_reduced w). Diagonal and cross terms were retained. Different weights define different responses, and cross terms were not interpreted as physiological interactions.

Specified combinations were KdpABC (K01546, K01547, K01548), KdpDE (K07646, K07667), ProVWX (K02000, K02001, K02002), EctABC (K06718, K00836, K06720), EctD (K10674) and BetAB (K00108, K00130). Calls distinguished none, some and all specified markers detected in a MAG; "all" did not mean a complete pathway or active system. Definitions requiring restored markers used the existing restoration presence calls. The exploratory common-support criterion required a lineage with at least two sources or sampling groups each containing five representatives, then retained all representatives in each eligible lineage. Quality and rank indicators formed the reduced model, and source or sampling-group indicators the full model. Descriptive degrees-of-freedom adjustment used 1 − [SSE_full/(n−rank_full)]/[SSE_reduced/(n−rank_reduced)]. It was not a holdout score or hypothesis test. Low state counts were flagged rather than used to select favourable endpoints.

### Additional dryland provenance and analogue scope

The additional catalogue was linked to PRJNA832417 field samples through deposited assembly parent records. Existing CheckM2, GTDB and full KOfam outputs were reused; no functional endpoints from digitized community plots entered this analysis. Bacterial representatives were selected after quality filtering, background flags and removal of ANI95 groups shared with the existing 4,095-genome comparison pool. Ranking used completeness minus five times contamination, followed by N50 and identifier. Primary and stringent selection were performed separately. The 13 primary and five stringent selected ANI groups occurring at multiple sampling labels retained their full label sets; exclusion of these groups provided a sensitivity analysis.

Reported parent latitude and longitude were parsed without correcting deposited positions. Great-circle distance used the haversine formula with radius 6371.0088 km; the maximum pairwise distance described each parent-sample group. Shared coordinates were not treated as evidence of exact co-location. The six regional candidates were prioritized in the regional scope review rather than selected by gene-state differences, but the audit followed inspection of catalogue outcomes and is explicitly retrospective. A bounded primary-literature audit recorded regional support, the studied locality and substrate, the relevant Mars analogy and correspondence limits. Analogue relevance was not converted to a severity score, and unresolved regional coverage was not treated as evidence of non-analogy. Common-lineage support was evaluated on metadata without loading functional responses. Existing site chemistry, transferred regional values and unmeasured quantities retained distinct evidence status; no missing resource values were imputed in this analysis.

'''
s=s.replace('### Bayesian functional-support models',insert+'### Bayesian functional-support models')
s=s.replace('This working revision supplies its environmental evidence table, carbon-route linkage, numerical figure inputs and rendering code locally.', 'This revision supplies environmental evidence and sampling-scope tables, carbon-route linkage, specified gene-combination definitions, paired reweighting outputs, numerical figure inputs and analysis code locally.')
a=s.index('## Figures and legends');b=s.index('## References',a)
s=s[:a]+'''## Figures and legends

![Constraint resource strategy framework](assets/figure1_framework.png)

Figure 1 | Environmental constraints, resource context and genomic strategies. Arrows denote hypotheses and evidence relationships, not fitted causal effects. Environmental measurements retain their original units and sampling levels. Water content, water activity, climatic aridity and conductivity are not interchangeable. Maintenance, energy acquisition and carbon assimilation can coexist within genomes. Life-detection and resource-use implications are conditional interpretations, not observed Martian outcomes.

![Paired uncertainty and aggregation sensitivity](assets/figure2_uncertainty.png)

Figure 2 | Paired uncertainty and aggregation sensitivity of the maintenance–energy contrast. A, Median contrasts and 95% conditional reweighting ranges under lineage-block weights and lineage-by-source product weights, separately for corrected core and restoration panels and quality strata. B, Primary bacterial module source partial R². C, Original primary contrast, omission of the solute and ion module and equal subgroup weighting of that module. Points in A and C are reweighting medians; original unweighted estimates are reported in the text. Module omission and reweighting are post-result diagnostics. The intervals do not represent uncertainty in a universal environmental effect, and percentage-point differences are not percentages of environmental explanation.

![Specified combinations and lineage support](assets/figure3_systems.png)

Figure 3 | Molecular decomposition and additional-catalogue support. A, Source partial R² for the five solute and ion subgroups in the original primary bacterial cohort. B, Fractions with all specified markers among genomes with any specified marker in stringent original and additional dryland sets, with conditional Bayesian reweighting ranges. Original weights operate on lineage blocks and new weights on sampling groups; ranges are not a formal between-population test. C, Number of representatives meeting the common-lineage support criterion in the additional dryland catalogue. Failure to meet the stringent order or family gate limits the comparison rather than demonstrating biological absence. Original source and new sampling-group associations are different estimands.

![Existing Bayesian source profile sensitivity](assets/figureS1_bayesian_profiles.png)

Supplementary Figure S1 | Existing Bayesian source-profile contrast and sensitivity. Points show posterior median differences in aggregate osmotic-marker support between Stordalen and Qaidam, with 95% credible intervals. Shared-family and prior sensitivities use overlapping data. The selected comparison is exploratory and the full endpoint output is retained. The aggregate endpoint is subject to the molecular composition and weighting limitations established in the main analyses.

Supplementary Table S1 | Deposited sample scope and regional Mars analogue evidence. The local table records all 25 dryland collection labels, 75 sample accessions, coordinates, dates, depths, parent-sample spans and primary/stringent representative counts. The accompanying literature table distinguishes evidence for a region or process from correspondence with the actual sampled substrate. The six-region audit subset is not a final inclusion list and the remaining labels are not certified negative controls.

'''+s[b:]
s+='''\n31. Sweet ME et al. Serine phosphorylation regulates the P-type potassium pump KdpFABC. eLife 2020;9:e55480. https://doi.org/10.7554/eLife.55480

32. Rubin DB. The Bayesian bootstrap. Annals of Statistics 1981;9:130–134. https://doi.org/10.1214/aos/1176345338
'''
s+='\n33. Navarro-González R et al. Mars-like soils in the Atacama Desert, Chile, and the dry limit of microbial life. Science 2003;302:1018–1021. https://doi.org/10.1126/science.1089143\n\n34. Azua-Bustos A et al. Inhabited subsurface wet smectites in the hyperarid core of the Atacama Desert as an analog for the search for life on Mars. Scientific Reports 2020;10:19183. https://doi.org/10.1038/s41598-020-76302-z\n\n35. Bishop JL et al. Carbonate rocks in the Mojave Desert as an analogue for Martian carbonates. International Journal of Astrobiology 2011;10:349–358. https://doi.org/10.1017/S1473550411000206\n\n36. Heldmann JL et al. The high elevation Dry Valleys in Antarctica as analog sites for subsurface ice on Mars. Planetary and Space Science 2013;85:53–58. https://doi.org/10.1016/j.pss.2013.05.019\n\n37. Ortiz M et al. Multiple energy sources and metabolic strategies sustain microbial diversity in Antarctic desert soils. Proceedings of the National Academy of Sciences 2021;118:e2025322118. https://doi.org/10.1073/pnas.2025322118\n\n38. Bourke MC, Viles HA. Valley floor aeolianite in an equatorial pit crater on Mars. Geophysical Research Letters 2016;43:12356–12362. https://doi.org/10.1002/2016GL071467\n\n39. Daniels J et al. Microwave remote sensing of physically buried objects in the Negev desert: Implications for subsurface Martian exploration. Journal of Geophysical Research: Planets 2003;108:8033. https://doi.org/10.1029/2002JE001868\n'
s=s.replace('Descriptive degrees-of-freedom adjustment used', '\n\nDescriptive degrees-of-freedom adjustment used')
s=s.replace('remain in the archived analysis 15 rather than being silently replaced', 'remain in the archived computational materials')
# Resolve numeric references from first appearance throughout the semantic source.
body,refs=s.split('## References',1)
refdict={int(m.group(1)):m.group(2) for m in re.finditer(r'(?ms)^(\d+)\. (.*?)(?=^\d+\. |\Z)',refs.strip())}
order=[]
for m in re.finditer(r'\[(\d+(?:,\s*\d+)*)\]',body):
 for v in map(int,re.findall(r'\d+',m.group(1))):
  if v not in order:order.append(v)
assert set(order)==set(refdict),(set(order)-set(refdict),set(refdict)-set(order))
renum={old:i+1 for i,old in enumerate(order)}
body=re.sub(r'\[(\d+(?:,\s*\d+)*)\]',lambda m:'['+', '.join(str(renum[int(v)]) for v in re.findall(r'\d+',m.group(1)))+']',body)
s=body+'## References\n\n'+'\n\n'.join(str(renum[k])+'. '+refdict[k].strip() for k in order)+'\n'
(D/'reference_number_map.json').write_text(__import__('json').dumps(renum,indent=2))
(D/'manuscript_v4.md').write_text(s)
for src,dst in [(B/'34_integrated_manuscript_20260929/assets/figure1_framework.png','figure1_framework.png'),(B/'48_MAG_portfolio_inference_20261001/host/portfolio_uncertainty_diagnostic.png','figure2_uncertainty.png'),(B/'49_system_configuration_20261001/host/system_configuration_diagnostic.png','figure3_systems.png'),(B/'34_integrated_manuscript_20260929/assets/figure3_bayesian_profiles.png','figureS1_bayesian_profiles.png')]:shutil.copy2(src,D/'assets'/dst)
print('v4 words',len(s.split()))
